version: "2"
services:
  antidote1:
     image: antidotedb/antidote:0.2.0
     ports:
       - "8087:8087"
     environment:
       NODE_NAME: "antidote@antidote1"
       SHORT_NAME: "true"
     cap_add:
       - NET_ADMIN
     networks:
       - interdc
       - local1

  antidote2:
    image: antidotedb/antidote:0.2.0
    ports:
      - "8088:8087"
    environment:
      NODE_NAME: "antidote@antidote2"
      SHORT_NAME: "true"
    cap_add:
      - NET_ADMIN
    networks:
      - interdc
      - local2

  server1:
    image: openjdk:12
    volumes:
      - ../bookstore/build/libs:/code
    command: "java -jar bookstore.jar 1"
    working_dir: /code
    cap_add:
      - NET_ADMIN
    networks:
      - local1

  server2:
    image: openjdk:12
    volumes:
      - ../bookstore/build/libs:/code
    command: "java -jar bookstore.jar 2"
    working_dir: /code
    cap_add:
      - NET_ADMIN
    networks:
      - local2

  link:
    image: erlang:19
    volumes:
      - .:/code
    command: '/code/link.sh'
    links:
      - antidote1
      - antidote2
    cap_add:
      - NET_ADMIN
    networks:
      - interdc

networks:
  interdc:
  local1:
  local2:
